root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/llm ./cmd/llm/llm.go"
  bin = "./tmp/llm"
  full_bin = "./tmp/llm"
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["assets", "tmp", "vendor", "frontend"]
  delay = 1000 # ms
  stop_on_error = true

[log]
  time = true

[misc]
  clean_on_exit = true
