root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/stt ./cmd/stt/stt.go"
  bin = "./tmp/stt"
  full_bin = "./tmp/stt"
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["assets", "tmp", "vendor", "frontend"]
  delay = 1000 # ms
  stop_on_error = true

[log]
  time = true

[misc]
  clean_on_exit = true
