services:
  auth:
    build:
      context: .
      target: dev
    volumes:
      - .:/app
    environment:
      - PORT=8081
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=notelytix
    ports:
      - "8081:8081"
    command: go run cmd/auth/main.go
    depends_on:
      - postgres

  stt:
    build:
      context: .
      target: dev
    volumes:
      - .:/app
    environment:
      - PORT=8082
      - SARVAM_API_KEY=sk_0cjogqsp_zKNGlV7gIKD3QOMOGyh5g0Ti
    ports:
      - "8082:8082"
    command: go run cmd/stt/stt.go

  meetings:
    build:
      context: .
      target: dev
    volumes:
      - .:/app
    environment:
      - PORT=8083
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=notelytix
    ports:
      - "8083:8083"
    command: go run cmd/meetings/main.go
    depends_on:
      - postgres

  llm:
    build:
      context: .
      target: dev
    volumes:
      - .:/app
    environment:
      - PORT=8084
      - GEMINI_API_KEY=AIzaSyAjAx7r41qP-m91TdM-1o0qcxIw-yDpGD8
    ports:
      - "8084:8084"
    command: go run cmd/llm/llm.go

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=notelytix
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
